name: "android-build"

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - "main"

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          submodules: "recursive"

      - name: "Set version string for release"
        run: echo DESTINY_VERSION=la_${{ github.ref_name }} >> $GITHUB_ENV
        if: ${{ github.ref_type == 'tag' }}

      - name: "Set version string for branch"
        run: echo DESTINY_VERSION=la_${{ github.head_ref }} >> $GITHUB_ENV
        if: ${{ github.ref_type != 'tag' }}

      - name: "Setup flutter"
        uses: "subosito/flutter-action@v2.3.0"

      - name: "Fetch flutter dependencies"
        run: "flutter pub get"

      # TODO remove the || true when this should be enforced
      # Right now it is just informational
      - name: "Lint"
        run: "flutter analyze || true"

      - name: "Style check"
        run: "flutter format --set-exit-if-changed lib test"

      - name: "Build release apk"
        run: "flutter build apk lib/main_la.dart -v --dart-define version=${{ env.DESTINY_VERSION }} --build-name ${{ env.DESTINY_VERSION }}"

      - name: "Copy apk"
        uses: "actions/upload-artifact@v2"
        with:
          name: "destiny-android-${{ env.DESTINY_VERSION }}-unsigned"
          path: "./build/app/outputs/flutter-apk/app-release.apk"
          if-no-files-found: "error"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./build/app/outputs/flutter-apk/app-release.apk"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref_type == 'tag' }}
