name: "android-build"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-apk:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          submodules: "recursive"

      - name: "Setup flutter"
        uses: "subosito/flutter-action@v1.5.3"

      - name: "Fetch flutter dependencies"
        run: "flutter pub get"

      - name: "Build release apk"
        run: "FLUTTER_HOME=$FLUTTER_ROOT flutter build apk lib/main_la.dart -v"

      # TODO remove the || true when this should be enforced
      # Right now it is just informational
      - name: "Lint"
        run: "flutter analyze || true"

      - name: "Style check"
        run: "flutter format --set-exit-if-changed lib test"

      - name: "Copy apk"
        uses: "actions/upload-artifact@v2"
        with:
          name: "destiny-android-${{ github.head_ref }}-unsigned"
          path: "./build/app/outputs/flutter-apk/app-release.apk"
          if-no-files-found: "error"
