name: "macos-build"

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  macos-build:
    runs-on: macos-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          submodules: "recursive"

      - name: "Set version string for release"
        run: echo DESTINY_VERSION=la_${{ github.ref_name }} >> $GITHUB_ENV
        if: ${{ github.ref_type == 'tag' }}

      - name: "Set version string for branch"
        run: echo DESTINY_VERSION=la_${{ github.head_ref }} >> $GITHUB_ENV
        if: ${{ github.ref_type != 'tag' }}

      - name: "Setup flutter"
        uses: "subosito/flutter-action@v2.3.0"

      - name: "Fetch flutter dependencies"
        run: "flutter pub get"

      # TODO remove the || true when this should be enforced
      # Right now it is just informational
      - name: "Lint"
        run: "flutter analyze || true"

      - name: "Style check"
        run: "flutter format --set-exit-if-changed lib test"

      # TODO maybe this can be avoided by some project configuration,
      # but running it locally doesn't change any files either.
      - name: "Enable macos desktop builds"
        run: "flutter config --enable-macos-desktop"

      - name: "Build mac app"
        run: "flutter build macos lib/main_la.dart -v --dart-define version=${{ env.DESTINY_VERSION }} --build-name ${{ env.DESTINY_VERSION }}"

      - name: "Install create-dmg"
        run: "brew install create-dmg"

      - name: "Create DMG"
        run: "create-dmg --app-drop-link 0 0 --eula LICENSE Destiny_LA_${{ env.DESTINY_VERSION }}.dmg build/macos/Build/Products/Release/dart_wormhole_gui.app"

      - name: "Copy DMG"
        uses: "actions/upload-artifact@v2"
        with:
          name: "destiny-macos-${{ env.DESTINY_VERSION }}-unsigned"
          path: "./Destiny_LA_${{ env.DESTINY_VERSION }}.dmg"
          if-no-files-found: "error"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./Destiny_LA_${{ env.DESTINY_VERSION }}.dmg"
          token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref_type == 'tag' }}
